name: $(BuildID)

trigger:
  branches:
    include:
    - main
    - production
  paths:
    exclude:
    - '*.md'
    - 'backends/*'
    - 'images/*'
    - '.github/*'

pr: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
  - template: vars/global.yaml
  - ${{ if eq(variables.isMain, 'True') }}:
    - group: e2e-gov-demo-dev-kv
  - ${{ if eq(variables.isProduction, 'True') }}:
    - group: e2e-gov-demo-kv

stages:
- template: templates/ci.yaml
- template: templates/deploy.yaml
