name: $(BuildID)

trigger:
  branches:
    include:
    - main
    - production
  paths:
    exclude:
    - '*.md'
    - 'backends/*'
    - 'images/*'
    - '.github/*'

pr: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
  - template: vars/global.yaml

stages:
- template: templates/ci.yaml
- template: templates/deploy.yaml
