# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
    - main
    - dev
    - feat/*
    - fix/*

pr:
- main

pool:
  vmImage: 'ubuntu-18.04'

steps:
- bash: terraform init
  displayName: init

- bash: terraform validate
  displayName: validate

- bash: terraform fmt -check
  displayName: check format / lint
