name: $(BuildID)

trigger:
  branches:
    include:
    - main
    - feat/*
    - fix/*
  paths:
    exclude:
    - '*.md'
    - 'backends/*'
    - 'images/*'
    - '.github/*'

pool:
  vmImage: 'ubuntu-18.04'

stages:
- template: stages/ci.yaml
