# Build numbering format
name: $(BuildID)

pool:
  vmImage: 'ubuntu-18.04'

trigger: none

pr:
- release

variables:
  - group: e2e-gov-demo-kv

stages:

# Stage: Terraform Plan
# ---------------------
- stage: TFPlanStage
  displayName: Terraform Plan
  jobs:
  - job: DetectDriftJob
    displayName: Detect Drift
    steps:
    - bash: |
        terraform init \
          -backend-config="storage_account_name=$TF_STATE_BLOB_ACCOUNT_NAME" \
          -backend-config="container_name=$TF_STATE_BLOB_CONTAINER_NAME" \
          -backend-config="key=$TF_STATE_BLOB_FILE" \
          -backend-config="sas_token=$TF_STATE_BLOB_SAS_TOKEN"
      displayName: Terraform - Init
      env:
        TF_STATE_BLOB_ACCOUNT_NAME:   $(kv-tf-state-blob-account)
        TF_STATE_BLOB_CONTAINER_NAME: $(kv-tf-state-blob-container)
        TF_STATE_BLOB_FILE:           $(kv-tf-state-blob-file)
        TF_STATE_BLOB_SAS_TOKEN:      $(kv-tf-state-sas-token)

    - bash: |
        # Remember Exit Code
        set -o pipefail

        # Run `terraform plan` and save output
        terraform plan \
          -detailed-exitcode \
          -var superadmins_aad_object_id=$AAD_SUPERADMINS_GROUP_ID \
            | tee plan-output.txt

        # Save Exit Code
        STATUS=${PIPESTATUS[@]}
        echo "##vso[task.setvariable variable=tfPlanExit]$("echo $STATUS")"
        [[ $STATUS == "0" ]] && exit 0 || exit 1
      displayName: Terraform - Detect configuration drift
      continueOnError: true  # so we can post result to Pull Request
      name: planStep
      env:
        ARM_SUBSCRIPTION_ID:        $(kv-arm-subscription-id)
        ARM_CLIENT_ID:              $(kv-arm-client-id)
        ARM_CLIENT_SECRET:          $(kv-arm-client-secret)
        ARM_TENANT_ID:              $(kv-arm-tenant-id)
        AZDO_ORG_SERVICE_URL:       $(kv-azure-devops-org-url)
        AZDO_PERSONAL_ACCESS_TOKEN: $(kv-azure-devops-pat)
        AAD_SUPERADMINS_GROUP_ID:   $(kv-aad-superadmins-group-id)

    - bash: echo "Exit Code - $(tfPlanExit)"
      displayName: Confirm Exit Code

    # # Multiline variables are not supported in Azure DevOps 😕
    # - bash: |
    #     echo "##vso[task.setvariable variable=tfPlanOutput]$(cat ./plan-output.txt)"
    #   displayName: Save terraform plan output

    # - bash: echo $(tfPlanOutput)
    #   displayName: debug tf plan output

# Stage: Pull Request Comment
# ---------------------------

- stage: PRCommentStage
  displayName: Post Results to GitHub
  # variables:
  #   github-repo-name:       Azure-Samples/devops-governance
  #   github-connection-name: Azure-Samples
  #   ado-org-name:           julie-msft
  #   ado-project-name:       e2e-governance-demo
  #   build-id:               $(BuildID) # ${{ variables['Build.BuildId'] }}
  #   has-drift:              ne('0', $[ dependencies.DetectDriftJob.outputs['DetectDriftJob.planStep.tfPlanExit'] ])
  # - name: has-no-drift
  #   value: eq($[ dependencies.TFPlanStage.result ], 'Succeeded')
  # - name: has-drift
  #   value: in($[ dependencies.TFPlanStage.result ], 'Failed', 'SucceededWithIssues')
  # - name: was-not-run
  #   value: in($[ dependencies.TFPlanStage.result ], 'Canceled', 'Skipped')
  jobs:
  - job: PostCommentJob
    displayName: Post Results to GitHub
    variables:
      - name: github-repo-name
        value: Azure-Samples/devops-governance
      - name: github-connection-name
        value: Azure-Samples
      - name: github_connection_name
        value: Azure-Samples
      - name: ado-org-name
        value: julie-msft
      - name: ado-project-name
        value: e2e-governance-demo
      - name: build-id
        value: $(BuildID) # ${{ variables['Build.BuildId'] }}
      - name: has-driftt
        value: ne('0', $[ dependencies.DetectDriftJob.outputs['DetectDriftJob.planStep.tfPlanExit'] ])
    # - name: has-drift
    #   value: ne('0', $[ dependencies.DetectDriftJob.outputs['DetectDriftJob.planStep.tfPlanExit'] ])
    # - name: tf-plan-output
    #   value: ${{ dependencies.DetectDriftJob.outputs['DetectDriftJob.planStep.tfPlanOutput'] }}
    steps:
    - task: GitHubComment@0
      condition: eq(variables['has-drift'], false)
      displayName: Post - No Drift
      inputs:
        gitHubConnection: $(github_connection_name)
        repositoryName: $(github-repo-name)
        comment: |
          🟢 No configuration drift detected

    - task: GitHubComment@0
      condition: variables['has-drift']
      displayName: Post - Has Drift
      inputs:
        gitHubConnection: $(github_connection_name)
        repositoryName: $(github-repo-name)
        comment: |
          ### ⚠️ &nbsp;Configuration Drift Detected

          Approving this Pull Request may result in destructive changes to your Azure resources. Please review the `terraform plan` configuration diff at Azure Pipelines:
          https://dev.azure.com/$(ado-org-name)/$(ado-project-name)/_build/results?buildId=$(build-id)&view=results

          Proceed with caution!