name: $(BuildID)

pool:
  vmImage: 'ubuntu-18.04'

trigger: none # PR only

pr:
- production

variables:
  - template: vars/global.yaml
  - group: e2e-gov-demo-kv # PROD

stages:
  - template: stages/ci.yaml
  - template: stages/pull-request.yaml
