name: $(BuildID)

pool:
  vmImage: 'ubuntu-18.04'

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  always: true
  branches:
    include:
    - main
    - production

variables:
- template: vars/global.yaml
- ${{ if eq(variables.isMain, 'True') }}:
  - group: e2e-gov-demo-dev-kv
- ${{ if eq(variables.isProduction, 'True') }}:
  - group: e2e-gov-demo-kv

steps:
- bash: |
    echo "KV_DEBUG_ENV: $KV_DEBUG_ENV"
    if [ "$KV_DEBUG_ENV" = '$(kv-debug-env)' ]; then
      echo "Key Vault not loaded. If loaded properly, debug env value would be 'dev' or 'production'."
      exit 1
    else
      echo "Key Vault loaded for: $KV_DEBUG_ENV"
    fi
  displayName: Key Vault loaded?
  env:
    KV_DEBUG_ENV: $(kv-debug-env)
- template: steps/debug-vars.yaml
- template: steps/terraform-init.yaml
- template: steps/terraform-plan.yaml
  parameters:
    extraFlags: -detailed-exitcode # Drift Detection