name: $(BuildID)

pool:
  vmImage: 'ubuntu-18.04'

trigger: none
pr: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily Midnight Build
    always: true
    branches:
      include:
      - main
      - production

variables:
  - template: vars/global.yaml
  - ${{ if eq(variables.isMain, 'True') }}:
    - group: e2e-gov-demo-dev-kv
  - ${{ if eq(variables.isProduction, 'True') }}:
    - group: e2e-gov-demo-kv

steps:
- template: steps/terraform-init.yaml
- template: steps/terraform-plan.yaml
  parameters:
    extraFlags: -detailed-exitcode # Drift Detection